apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-configmap
data:
  fluent-bit.conf: |
    [INPUT]
        Name cpu
        Tag cpu
    [OUTPUT]
        Name s3
        Match *
        tls.verify false
        #log_key log
        bucket ntrwsms/portal
        endpoint https://minio:30000
        total_file_size 1M
        store_dir /data/ec2-user/buffer
        s3_key_format /testing/cpu.log
        static_file_path true


---
apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit
spec:
  hostAliases:
  - ip: "ip"
    hostnames: [ "minio" ]
  containers:
  - name: fluent-bit
    image: fluent-bit:2.1
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "AWS_ACCESS_KEY_ID"
    - name: AWS_SECRET_ACCESS_KEY
      value: "AWS_ACCESS_KEY_ID"
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    volumeMounts:
      - mountPath: /fluent-bit/etc/
        name: config-fluent
  volumes:
    - name: config-fluent
      configMap:
        name: fluent-bit-configmap
